### ISSUE TITLE
[Mod] petResponseDTO 수정

### ISSUE THREAD

**Issue by wnsgho** [prgrms-web-devcourse-final-project/WEB1_2_TenPaws_BE#125]
## 🎯 작업 설명
- petResponseDTO boolean 타입 수정하겠습니다.
- shelter address, name 추가 하겠습니다.

## ✅ 작업 상세 내용
- petResponseDTO boolean 타입 수정
- shelter address, name 추가

## 📌 참고사항
(참고사항을 작성해주세요 !)

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Modified PetResponseDTO to change boolean types to Boolean and updated ShelterResponseDTO to include shelter name and address.

You can review changes in this commit: https://github.com/mnmnk43434/prgrms-web-devcourse-final-project-WEB1_2_TenPaws_BE-125/commit/51dcc0babe54c7838bfa618ac91ebbb41ebc3401.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.
